python segment_deyo.py \
    --sync-bn \
    --workers 4 \
    --device 0 \
    --batch 90 \
    --data data/coco.yaml \
    --img 160 \
    --cfg models/segment/gelan-c-seg-detr.yaml \
    --weights 'weights/gelan-c-seg.pt' \
    --name "train_seg" \
    --hyp data/hyps/deyo.yaml \
    --epochs 10 \
    --close-mosaic 10 \
    --freeze 22 \
    --no-overlap \
    --optimizer AdamW
